### PR TITLE
Add fix for score screen casualties count for Soviets sometimes showing up with blue color instead of red

### PR DESCRIPTION
**Pull request by mvdhout1992**
This always happens on first Soviet campaign mission end.

### CODE REVIEW

**Comment by hifi** [comment]
This is only a small nitpick that I sometimes forget myself as well is that local variables should be in snakecase in the C&C source.

**Comment by mvdhout1992** [comment]
> 
> 
> This is only a small nitpick that I sometimes forget myself as well is that local variables should be in snakecase in the C&C source.

Will update that.

**Review by OmniBlade — APPROVED** [review]
Needs to be rebased and clang format applied to pass the CI, but otherwise does what it says on the tin.

**Comment by hifi** [comment]
I guess the correct formatting would be `is_soviet_player` for the variable but it's fine as it is. Just rebase for merge.

**Pull request merged**
