### PR TITLE
WWKeyboardClass' KeyState buffer is Win32 only, so mark it as such.

### PR DESCRIPTION
**Pull request by isojalka**

### CODE REVIEW

**Comment by th-otto** [comment]
This fix is also needed for all platforms using SDL1, because VK_SHIFT aka SDLK_SHIFT has the value 304 and will overflow the KeyState buffer

**Comment by isojalka** [comment]
This change is actually just a smaller part of work I did to clean up the input code to make it possible to properly support multiple platforms, including splitting the SDL1 and SDL2 code so that they can both be properly supported in the code base.

Unfortunately this pull request was never merged, so this work currently only exists in my MorphOS port of Vanilla Conquer. If this pull request eventually gets merged, I might see if it's still possible to also get the rest of my changes merged without too much effort.

**Comment by th-otto** [comment]
Thanks for the explanation.

Yes, i noticed that this PR was not merged yet.

For the record: i'm currently working on (mostly smaller) patches for an Atari/FreeMiNT port. Using SDL1 was no problem so far (there is no SDL2 for Atari yet).  That patch currently also has some of your other PRs applied that are not yet merged (ie. the ones fixing endian issues). But i also had some other things to fix which IMHO also affect MorphOS, ie. Program_Path returns an empty string, which is then later concatenated with some sub-directory names, resulting in lookups of ie. `/gdi`. With all my patches applied (see the PRs i just opened) it now starts up, but there is one problem remaining when trying to move units (they start animating, but simply don't move). Maybe some more endian issues?

BTW is there some branch in your fork with all your patches applied? I only find several branches with single commits where you created the PRs from.

**Comment by isojalka** [comment]
Well, this pull request has now been merged. Thank you very much, @hifi!

I've also pushed a branch called 'merged_branch' to my own fork of Vanilla Conquer. It includes all changes and code for the MorphOS port of Vanilla Conquer. You can find it here: https://github.com/isojalka/Vanilla-Conquer/tree/merged_branch

The source code is also included in the MorphOS port I [released here](https://bigfoot.morphos-team.net/files/) in case you want the exact source code I used for those releases.

**Pull request merged**
