### PR TITLE
Fixes radar movement of opponents being revealed.

### LINKED ISSUE #720: Vanilla TD: Can see what the enemy has explored on the minimap in MP game
image

Steps to reproduce
1. Play MP with another player
2. Build radar
3. See what the enemy does and has done...

Kinda interesting feature for a C&C like game, but for C&C this is quite incorrect.

### PR DESCRIPTION
**Pull request by OmniBlade**
Currently a provisional fix that needs testing.
Fixes #720

### CODE REVIEW

**Comment by giulianobelinassi** [comment]
I am not sure how I feel about it. Shouldn't allies also reveal terrain to mimic how remaster works? The presented patch only reveals the map for the current player.

**Comment by OmniBlade** [comment]
The logic for that should be revealing it to the PlayerPtr still though after checking if another house is allied. It shouldn't be revealing for any player that happens to be human controlled. Concerns like that are why it is provisional though and needs testing in both SP missions with allied side that would normally reveal shroud and in MP.

**Comment by mvdhout1992** [comment]
In the original game it doesn't reveal for anyone but the player itself (not even allies), I added the ally shroud reveal as option to CnCNet.

**Comment by OmniBlade** [comment]
Merging after discussion with @giulianobelinassi as initial bug is confirmed fixed by this PR and is subject to further testing to ensure no other issues.

**Pull request merged**
