### PR TITLE
Implements Buffer_Print in C++.

### PR DESCRIPTION
**Pull request by OmniBlade**
No test again here due to linking GraphicBufferClass in common.

### CODE REVIEW

**Comment by wdigger** [comment]
So the problem with my request was not with the test at all.
It's sad.

**Comment by OmniBlade** [comment]
Your PR removed the ASM version entirely which was the main issue I believe. This version can be switched back to the ASM if a bug was noticed so at least we can test it by eyeballing it.

**Comment by wdigger** [comment]
We have version control for this in the 21st century, I don’t know about you.
The only reason to leave ASM was tests, at least according to you. It turns out that this is not entirely true.

**Comment by OmniBlade** [comment]
Indeed, so keeping it in the current working revision so the code can be differentially compiled without having to check out older versions of a single file and add a bunch of changes to the build system everytime we want to revert to test an ASM function behaviour isn't costing us any extra disk space.
In my comments on your PR I tried to make it clear the primary reason to keep the ASM was to be able to rebuild any given commit swapping the C/C++ code implementations for the ASM ones and vice versa. You may disagree with that policy, but its a couple of extra lines to add the preprocessor macros to support it so I don't see what the issue is.

**Comment by hifi** [comment]
Is writing the test now possible with the fixes from #117?

**Comment by OmniBlade** [comment]
Should now be testable with a few bits of data embedding.

**Comment by hifi** [comment]
Since testing this requires game data or a free version of the font I think we can leave the test out for now.

**Review by hifi — APPROVED** [review]

**Pull request merged**
