### PR TITLE
Moves more code to common.

### PR DESCRIPTION
**Pull request by tomsons26**

### CODE REVIEW

**Review by hifi — CHANGES_REQUESTED** [review]
We should not move code to common that is not already shared by the games.

What I mean here is wsproto and crc stuff. Especially lib.cpp as it has a different/legacy implementation of HSV/RGB stuff that's done much better in RA than TD and should be refactored in TD instead.

**Comment by tomsons26** [comment]
> We should not move code to common that is not already shared by the games.
> 
> What I mean here is wsproto and crc stuff. Especially lib.cpp as it has a different/legacy implementation of HSV/RGB stuff that's done much better in RA than TD and should be refactored in TD instead.

Hm actually crc can just go, i moved it thinking it will be of use for when INIClass is shared with RA and TD but its not used at all in any WW game.
wsproto would be needed by TD in the future no?
lib, well yeah true

**Comment by hifi** [comment]
RAMFileClass is also used only within RA.

**Review by hifi — APPROVED** [review]
Looks good to me now

**Pull request merged**
