### PR TITLE
[RA] Restores TD stealth effect for land units.

### PR DESCRIPTION
**Pull request by OmniBlade**
The TD stealth effect is restored for RA which is mainly evident on the aftermath missions involving the phase transport in the unmodded game. It will also apply to crate based stealth power ups if enabled as well as units modded to have stealth.

### CODE REVIEW

**Comment by hifi** [comment]
Is this considered a visual improvement? I'm not familiar with this effect or it being missing so I believe @tomsons26 is a better candidate to review this functionality wise.

**Comment by OmniBlade** [comment]
I consider it to be, but like any change it may be controversial. In my opinion the effect as it exists by default is intended only for submarine units. For example the phase transport shadow becomes green during cloaking because code doesn't pass a fading table to the draw code and doesn't need to for subs because they don't have a shadow. The code just restores what was commented out and does so conditionally for none naval units for what is again in my opinon a superior effect and one that is more consistent with cloaking in TD.

**Comment by TobiasKarnat** [comment]
Very nice improvement, even visible in remastered. But it causes a bug in remastered, I think you also need to exclude buildings.

grafik

**Comment by OmniBlade** [comment]
Odd that it affects the remaster renderer, I wouldn't expect it to but it guess it's related to the intercepted draw calls. I'll exempt buildings in the remaster as well then I guess, is this not an issue in TD?

**Comment by OmniBlade** [comment]
Okay, fixed the remaster issue, thanks for pointing them out @TobiasKarnat.

**Review by tomsons26 — APPROVED** [review]

**Comment by hifi** [comment]
Would be nice if @TobiasKarnat could verify this is fixed on remaster before merging?

**Comment by OmniBlade** [comment]
I've tested it myself on remaster, but a second opinion confirming it would be welcome.

**Comment by TobiasKarnat** [comment]
Sure, I build always with this patch the last weeks. Works perfect, doesn't break anything.

**Pull request merged**
