### PR TITLE
Adds Skirmish mode to standalone TD.

### LINKED ISSUE #203: VanillaTD Skirmish mode
The Remaster build supports a skirmish mode for TD via the glyphx frontend, but the vanilla menu system currently has no way of going into skirmish mode. In RA the Serial menu pulled double duty and also acted as the skirmish menu which is now its sole role. The TD menu could perhaps be refactored in a similar fashion.

### PR DESCRIPTION
**Pull request by OmniBlade**
Creates a skirmish mode accessible from the standalone build in TD.

### CODE REVIEW

**Review by hifi — CHANGES_REQUESTED** [review]
Just so that it isn't forgotten, as I said on Discord the gameplay doesn't pause when you open the options menu like it does in SP.

**Comment by OmniBlade** [comment]
Pausing is fixed, centering on your units and color matching the remap are still outstanding on this PR, but skirmish is playable as is otherwise.

**Comment by Gerwin2k** [comment]
VanillaTD.exe, Win32, DirectDraw. GDI Skirmish: Minimap remains black regardless of Comm.+power.

**Comment by OmniBlade** [comment]
@Gerwin2k I've fixed the radar issue, the only outstanding issue now should be the in game units getting the wrong remap colors.

**Comment by OmniBlade** [comment]
@hifi I think this PR is ready to consider for merging.

**Review by hifi — CHANGES_REQUESTED** [review]
The game works, I skimmed through the changes.

However, keyboard navigation in the multiplayer menu when networking is disabled or at least on Linux is broken in two ways: selecting with cursor goes through invisible button and hitting enter causes a segfault. I just fixed a similar bug I introduced with the demo changes to intro button in RA main menu.

After this is fixed I'm going to approve this so this can be refined in the vanilla branch if therre's still more work that needs to be done.

**Comment by OmniBlade** [comment]
> 
> 
> The game works, I skimmed through the changes.
> 
> However, keyboard navigation in the multiplayer menu when networking is disabled or at least on Linux is broken in two ways: selecting with cursor goes through invisible button and hitting enter causes a segfault. I just fixed a similar bug I introduced with the demo changes to intro button in RA main menu.
> 
> After this is fixed I'm going to approve this so this can be refined in the vanilla branch if therre's still more work that needs to be done.

The menu navigation should be fixed now as well.

**Review by hifi — APPROVED** [review]
Okay, game works and menu now works, let us merge!

**Pull request merged**
