### PR TITLE
Removes most of Null modem code.

### PR DESCRIPTION
**Pull request by tomsons26**

### CODE REVIEW

**Comment by OmniBlade** [comment]
The Com_Scenario_Dialog is required in RA for the skirmish screen. With there being some AI in TD now we may also want to keep it there to be modified into a skirmish dialog as well.

**Comment by tomsons26** [comment]
> The Com_Scenario_Dialog is required in RA for the skirmish screen. With there being some AI in TD now we may also want to keep it there to be modified into a skirmish dialog as well.

Restored the cpps, left them with if 0's

**Review by OmniBlade — APPROVED** [review]
Doesn't seem to have broken anything at my end.

**Review by hifi — APPROVED** [review]
There's quite a bit of unnecessary stuff in nulldlg in TD but I suppose it's hard to cherry pick what to leave until a skirmish dialog exists or something like it.

In Nyerguds patch a skirmish game is just a LAN game with one player if I recall correctly but probably better to use the modem dialog like RA skirmish.

**Pull request merged**
