### PR TITLE
Fix Tesla Coil bolt rendering way too many bolts in VanillaRA standalone

### PR DESCRIPTION
**Pull request by mvdhout1992**
This also fixes the Tesla Coil zap effect rendering from weird angles on the screen because unlike 3.03 the original remaster code doesnt adjust the x and y coordinates of both src and destination coordinates for being in tactical view or not (because in remaster it ignores tactical view constraints and renders the game at a resolution equal to max map size).

I wasn't able to fix Remaster Tesla Coil rendering. From my testing it is likely that it's something inside the Glyphx layer that is preventing me from fixing it for Remaster.

### CODE REVIEW

**Comment by ghost** [comment]
@mvdhout1992 can you add to PRs which are changing behavior a short gif with "before" and "after"? After that for getting a review you would only need a dev who knows c++, instead of dev who knows c++ and c&c.

**Comment by hifi** [comment]
Rebased and reformatted

**Comment by OmniBlade** [comment]
Fixes #166

**Comment by OmniBlade** [comment]
After testing this I feel it goes too much the other way and in some cases the bolt doesn't even draw at all for me.

**Comment by OmniBlade** [comment]
I believe this may have been incidentally fixed by other fixes and now this PR actually prevents the bolt drawing correctly. Closing for now.

**Pull request closed without merging**
