### PR TITLE
Valgrind fixes

### PR DESCRIPTION
**Pull request by cg9999**
I've done some debugging with valgrind and fixed some issues. I will probably continue in a few days, as there are still several issues left.
These are mostly to common or [TD], as I have not yet a working installation for [RA]. Some fixes have been also applied to RA tree, where the code was basically identical.
Please see if you agree with my methods for fixing these issues.

### CODE REVIEW

**Review by OmniBlade — CHANGES_REQUESTED** [review]
Looks like you need a const cast at the very least in profile.cpp to pass the CI.

**Comment by cg9999** [comment]
I added a c-style cast on the RA patch to retain consistent code style. Same construct is used a few lines ahead there.

**Review by OmniBlade — APPROVED** [review]

**Review by hifi — APPROVED** [review]
Yeah, looks good to me. You need to rebase, though.

**Comment by cg9999** [comment]
Rebased without further changes, so I think it should be ready to merge when the checks are complete.
I think this also fixes #209, as I don't seem to get corruption to CONQUER.INI anymore. Tried changing the game speed settings etc.

**Comment by hifi** [comment]
Indeed, I think it does fix that.

**Pull request merged**
