### PR TITLE
Fix compilation of the editors when using SDL1

### PR DESCRIPTION
**Pull request by th-otto**
SHIFT-HOME and HOME have the same values for SDL1; use CTRL-HOME instead

### CODE REVIEW

**Comment by th-otto** [comment]
Hm, build fails in the clang format check, but the lines that are marked (https://github.com/TheAssemblyArmada/Vanilla-Conquer/actions/runs/8308506496/job/22740736584#step:7:810) are not touched by the patch?

**Comment by OmniBlade** [comment]
Looks like the added ifdef is confusing clang-format? Maybe add a line break after the comment block and see if that makes it happy?

**Comment by th-otto** [comment]
Nope, didn't work.

**Comment by th-otto** [comment]
But moving the block inside the ifdef worked. I guess clang-format wants the comment to be aligned with the case label, and got confused by the preprocessor statement.

**Review by OmniBlade — APPROVED** [review]

**Pull request merged**
