### PR TITLE
Collecting timer related stuff in common

### PR DESCRIPTION
**Pull request by wdigger**
Unfortunately, many changes were made :(
But it is better to do this now, since it allows to continue to bring many other things into the common code.

### CODE REVIEW

**Review by tomsons26 — CHANGES_REQUESTED** [review]
Can't approve this, sorry.
Try moving the timer code to common, don't touch their use places.

Timing related code all needs to be carefully reviewed, there are places the wrong timer is used in originals, places where a specific timer use fails on modern faster systems to provide the expected behavior and lots of other underlaying issues, we discovered this working on Chronoshift.
If you need help in figuring out how to commonize something in the timer code ask @OmniBlade or me on Discord.

**Comment by OmniBlade** [comment]
I have to agree with @tomsons26 that as it stands this PR is too large in scope to easily review and test. The timers are in general a good target to be moved to common and standardised on as ultimately they all depend on the same time sources anyway, but I think it could be done in a more incremental fashion.

For example the API change to the newer timers `Value()` call from the `Time()` call could be done without actually changing the underlying timers and each individual timer that isn't the correct type could be moved to the correct one in a separate commit or preferrably from a review point of view, a PR.

As @tomsons26 says the ones you want to use as the common timer source could also be moved to common in a single commit without changing anything else, again improving reviewability and making it easier to track any regressions with git bisect.

**Comment by wdigger** [comment]
Easy.
Breaking not building.

**Comment by tomsons26** [comment]
Don't remove any code or comments, just move it to common. Don't merge stuff into one header either. NoInit should be in its own header noinit.h to eliminate the nasty duplications.

**Comment by wdigger** [comment]
The point was to have the same timers in both projects.
The requested changes completely devalue the work.
I close it.

**Pull request closed without merging**
