### PR TITLE
Update README and refresh CMakeLists

### LINKED ISSUE #207: MinGW cross-compiling consistently freezes my entire computer
Every time. No idea what else to say about it other than that I'm running it on Arch, cause I don't think there's a way to get a log out of that

### PR DESCRIPTION
**Pull request by hifi**
Set Vanilla as the default and only target by default, reorder
README so that it is preferred over Remaster.

Windows builds now default to SDL2 and OpenAL. Networking is now
disabled on CI until we make it work because the CI artifacts are
used for testing and they wouldn't represent the testable state.

Dropped Wine checking and setting the emulator because the test
was wrong and we don't need to run tests with Wine anymore on
Linux.

Use CMake feature summary for displaying enabled/disabled
features.

These changes make all builds equal feature wise by default.

### CODE REVIEW

**Comment by hifi** [comment]
Input on this @OmniBlade @tomsons26?

**Comment by OmniBlade** [comment]
The bit about the remasters should probably also include what is required for the TD dll to work correctly with the megamaps extension that @TobiasKarnat mentioned in discord.

**Comment by hifi** [comment]
> The bit about the remasters should probably also include what is required for the TD dll to work correctly with the megamaps extension that @TobiasKarnat mentioned in discord.

Can you elaborate on this a bit more?

**Comment by TobiasKarnat** [comment]
That is a mixed bag. I would prefer MegaMap support and it is working with skirmish maps. But it breaks for single player maps (that mentioned map in discord).

I think it needs further research why it breaks with single player in remastered, just disabling this feature in remastered is only a workaround (by removing the MEGAMAPS from tiberiandawn/CMakeLists.txt).

**Review by OmniBlade — APPROVED** [review]
So I'm going to approve this as is for now and we can pick up the issues with megamaps and the remaster later.

**Pull request merged**
