### PR TITLE
Ubuntu-based workflows updated to latest versions

### PR DESCRIPTION
**Pull request by MLipfert1**
Ubuntu 18.04 is deprecated by GitHub. I updated the workflows to the latest Ubuntu-versions and fixed the formattings of some files. Otherwise clang-format-14 would fail.

### CODE REVIEW

**Comment by OmniBlade** [comment]
Can you bump the clang-format version a little less? Say Clang-format12 so its still useable on 20.04 as well which is still supported without having to add 3rd party repos?

**Comment by MLipfert1** [comment]
The clang-format version should not really matter as it is only used in this workflow for checking the source code files for a proper and nice formatting. You should still be able to compile it with lower clang versions, even if the code has been formatted with clang-format-14.

The format adjustments of my second commit would also be required with clang-format-11.

**Comment by OmniBlade** [comment]
Except that if you are committing code you need to have used matching formatting which is easier if you can use the same version of clang-format the CI uses locally.

**Comment by MLipfert1** [comment]
I set the the clang-format version to "12" for the Linux workflow. I also did a quick fix for the Windows workflow, to install the correct ImageMagick version in any case.

**Review by OmniBlade — APPROVED** [review]

**Pull request merged**
