### PR TITLE
Fixes mouse in remaster and rendering in TD

### LINKED ISSUE #44: Cursor not visible in Remaster TD before alt-tab
This seems like a regression as it was working way back in the start.

Reproducible at least with mingw.

### PR DESCRIPTION
**Pull request by wdigger**
Closes #44 and #45.

### CODE REVIEW

**Review by OmniBlade — COMMENTED** [review]
I'm not sure why this is a better solution than just building the common library twice to generate a remaster version and standalone version of the common library, you are duplicating a source file that has the same contents. A better solution would be to have common which has code that compiles identically, then commonv and commonr that are the final linked libraries that build common code that needs different build configuration for remaster or standalone if you are really concerned about building source files more than once needlessly.

**Comment by wdigger** [comment]
Common project contains code common for all projects and it's must building once. Including mouseww in to this projects is a mistake.
Good idea to move such files to middle-ware common project buildable twice for remaster and legacy, but right now we have no such project and moving file back it's a relevant solution.

**Comment by OmniBlade** [comment]
I think the solution that involves the least changes is the more practical and the common part of the build was never intended to only contain code that is compiled once, we always expected some code would need to be compiled differently for the remaster builds vs the vanilla build. It was intended to just contain code that was shared between the two games. I'm all for optimising the build process, but for now reduplicating code seems like the more drastic solution.

Can you split this into two PRs so the fixed legacy rendering can be considered and tested separately?

**Comment by wdigger** [comment]
No chance.

**Pull request closed without merging**
