### PR TITLE
Fix memory leak in house.cpp

### LINKED ISSUE #650: [TD] HouseClass destructor is never called
The HouseClass destructor are never called, resulting in (small) memoryleak every time a game is loaded.

### PR DESCRIPTION
**Pull request by giulianobelinassi**
There was a memory leak on HouseClass unit trackers because the
HouseClass destructor were not being called. Furthermore, it gets
very complicated to track all allocations of HouseClass in the code
to release them all properly.

This commit refactors the unit trackers and the houseclass so dynamic
memory allocation of the trackers are not necessary by passing the array
size as a template argument, resulting in no destructor requirement for
HouseClass, fixing the memory leak without ugly hacks.

Closes #650

### CODE REVIEW

**Comment by tomsons26** [comment]
HouseClass DTOR is called by Remove_AI_Players, seems the Player's HouseClass is not meant to be deleted, this does present a problem of this leak yes, problem with it is the player stats can be carried over in some ways to the next session, this would be why they don't delete it, this is actually a potentially pretty deep rabbit hole.
I suppose simplest solution would be PlayerPtr->Free_Unit_Trackers(); after Remove_AI_Players

Looking at YR binary, they do just call the dtor on all HouseClass instances, maybe doing just that works without any affects on carryover stuff, not sure.

**Comment by giulianobelinassi** [comment]
> HouseClass DTOR is called by Remove_AI_Players, seems the Player's HouseClass is not meant to be deleted, this does present a problem of this leak yes, problem with it is the player stats can be carried over in some ways to the next session, this would be why they don't delete it, this is actually a potentially pretty deep rabbit hole.
> I suppose simplest solution would be PlayerPtr->Free_Unit_Trackers(); after Remove_AI_Players

I see. The call to the destructor is in `Clobber_All()`. I wonder if something has to be changed in this PR because calling the default ctor now still result in the release of the entire object, including the unit trackers, as these are now embedded within the HouseClass object (no pointers required).

If the trackers are used for some kind of carryover, then there should be a copy (or access) of the UnitTrackers somewhere in the code. But I can't find any in `tiberiandawn`, `redalert`, or `common`, only access to them in `stats.cpp` source -- which is never  compiled in the fist place -- and in the remaster's DLL interface. Therefore, there is no reason why this should impact the carryover logic.

Furthermore, I wonder if these objects can simply be guarded by the REMASTER macro.

> 
> Looking at YR binary, they do just call the dtor on all HouseClass instances, maybe doing just that works without any affects on carryover stuff, not sure.

I didn't change the logic about how or when the HouseClass dtor is called. My approach rely on the fact that the UnitTrackers `new` operator is never called, as the objects are now embedded in the HouseClass itself.

**Comment by hifi** [comment]
The comments indicate these were added for remaster so I think it would make sense to ifdef wrap them. They didn't really need to care about one time memory leaks with remaster as the game dll is loaded per played map.

This refactor also removes the need to build utracker completely which speeds up compile times a bit with remaster ifdefs.

The hard part here is testing, I have no idea how these can be tested with remaster. We might need to only rely on code review if the game doesn't crash.

**Comment by giulianobelinassi** [comment]
Done. Wrapped the utrackers with REMASTER_BUILD.

**Comment by giulianobelinassi** [comment]
I did a smoke test on remaster and it worked flawlessly.

**Comment by hifi** [comment]
My mistake to say the utracker code was remaster specific. The comments and code clearly state they were for internet games back then. However we are not tapping into that code right now because the Westwood Chat code in TD is all but gone and in RA the Westwood Online bit is going to be removed anyway. Though we will likely want to collect statistics for CnCNet style games with the spawner code so it's not necessarily completely useless.

Not sure if we should keep the ifdefs or not even though I asked for them.

**Comment by OmniBlade** [comment]
I think we need to reconsider the gating behind the remaster as as @hifi says we will probably want to use the trackers to generate the gameres packet and stats.cpp is in fact compiled in the networking PR. Where is the fault in the logic that is leaking the unit tracker memory anyhow, looks like if they are initialised they get deleted on HouseClass destruction. Are they getting passed around or is HouseClass responsible for them? Infact currently they should only ever be constructed for the remaster which unloads the dll anyhow as the game never runs as GAME_INTERNET currently.

**Comment by giulianobelinassi** [comment]
Updated. Removed those REMASTER_BUILD guards and updated stats.cpp as well.

**Comment by OmniBlade** [comment]
@giulianobelinassi Can we get a rebase on this now that the networking stuff is merged?

**Comment by giulianobelinassi** [comment]
Rebased.

**Comment by OmniBlade** [comment]
Thanks, I plan to give it a quick playtest and then merge this.

**Review by OmniBlade — APPROVED** [review]

**Pull request merged**
