### PR TITLE
[RA] Remove LZO compression support

### PR DESCRIPTION
**Pull request by hifi**
LZO compression was only used for saves and is only marginally
better for them than LCW. The implementation is not 64-bit safe
and is quite hefty.

Saves are now compressed with LCW which still achieves files that
are almost the same size.

Commented out LCWPipe/LCWStraw next to LZO in saveload.cpp also
indicate the developers were originally planning to use LCW but
for some reason decided to bring in LZO support instead.

We could also make them uncompressed but since we still have a
working compressor that we are required to keep around for other
purposes it fits the bill nicely.

This supersedes #236.

### CODE REVIEW

**Comment by JohnsterID** [comment]
For reference as well: https://github.com/electronicarts/CnC_Remastered_Collection/blob/master/CnCTDRAMapEditor/Utility/WWCompression.cs

**Comment by OmniBlade** [comment]
@JohnsterID Looks like Petroglyph used Nyerguds implementation which is basically a C# translation of the code I wrote for Chronoshift (The comment block explaining the format is taken verbatim from it) which is only slightly different from the code we have here.

**Comment by JohnsterID** [comment]
I should be clearer, that was for a laugh considering Nyer and you are referenced. Sorry.

**Comment by OmniBlade** [comment]
LOL, I thought it was a serious suggestion, which makes it all the funnier I guess :D

**Review by OmniBlade — APPROVED** [review]
Saving is a bit slower as LCW compressor is brute force, but works otherwise and is better than crashing during saving.

**Pull request merged**
