### PR TITLE
[TD] Added frame limiter to mission ending text, making it actually display in-game

### PR DESCRIPTION
**Pull request by hazelnot**

### CODE REVIEW

**Comment by hifi** [comment]
Looks like Do_Lose needs the same treatment.

**Comment by hazelnot** [comment]
Ah alright, fixed it.

**Review by hifi — APPROVED** [review]
Looks good to me now.

**Comment by hifi** [comment]
Though, can you squash these commits into one? Thanks.

**Comment by hazelnot** [comment]
~~I tried to but instead now there's four commits I have no idea how to actually do this~~

Ok I asked a programmer friend and now I know, I'll do it tomorrow

**Comment by hazelnot** [comment]
Ok I finally figured out how to squash commits, should be done now

**Pull request merged**
