### PR TITLE
Fixed some crashes

### PR DESCRIPTION
**Pull request by wdigger**

### CODE REVIEW

**Review by hifi — CHANGES_REQUESTED** [review]
Use `snprintf` when writing to a buffer with static size.

**Comment by wdigger** [comment]
Better use stringstream, if we want to change the original code.

**Comment by wdigger** [comment]
`stringstream` too progressive for this project, I hope `size_t` is not.

**Comment by hifi** [comment]
You went way overboard with this. Just use `snprintf` instead of `sprintf` and make sure it uses the real char array length. No reason to make it overly complex when it will not overflow ever in normal use and it's just a safety precaution.

**Comment by wdigger** [comment]
I still underestimate your fear of change, I hope someday I will understand this logic.

**Comment by wdigger** [comment]
I added one more commit.

**Review by OmniBlade — APPROVED** [review]
The TD map select doesn't look like it correctly does the color change on the mission select which represents the balance of power, but it no longer crashes so the campaign can be continued which is an improvement. I'll approve as is unless Yury wants to investigate the colour thing for this PR as well.

**Comment by wdigger** [comment]
Target of this PR is make it possible to go ahead with testing next missions.
Good catch about colouring, I may take a look on it in future PR's.

**Review by hifi — APPROVED** [review]

**Pull request merged**
